### PR TITLE
Make package structure

### PR DESCRIPTION
**Pull request by krzyslom**
This creates package structure and sets basic information about package.

### CODE REVIEW

**Comment by dokato** [comment]
I would avoid names of scripts with dot: such a file would be impossible to open for Windows users I guess: `shiny.i18n.R`. My suggestion for now: `main.R`.

**Comment by dokato** [comment]
Are `vignettes` added by default? They're not at the highest priority at the moment, so I would skip them.

**Comment by krzyslom** [comment]
As for `shiny.i18n.R` I've read at http://r-pkgs.had.co.nz/man.html – "I usually put this documentation in a file called <package-name>.R. It’s also a good place to put the package level import statements that you’ll learn about in imports." Maybe shiny-i18n.R will be fine? There is no strong principle on this topic? What about Rproj file in this context?

As for vignettes – the directory has been deleted.

**Comment by dokato** [comment]
Good point, but let's skip it for now. Now package structure looks okay 👍

**Pull request merged**
